### ISSUE TITLE
No iscc command found on macOS High Sierra (10.13.6)

### ISSUE THREAD

**Issue by luli0822** [iscc/iscc-cli#20]
Hello,

I have installed iscc-cli via `pip3 install iscc-cli` on my macbook, but i can not run iscc. Can you help me with this?

**Comment by titusz** [comment]
It will depend on how you have your python installation configured. If you run an interactive python shell (with the python version to which you installed the package) you should be able to find the installation path of the `iscc` command line script like this:

```
>> import sysconfig
>> sysconfig.get_path('scripts')
```

**Comment by luli0822** [comment]
I don't why but I just rebooted my mac and now it works. 
Close this and hopefully other people who may encounter similar issue can try to reboot and see how it's going.

Thanks a lot for your support anyways, @titusz.
